INSERT INTO aircraft (aircraft_id, model, manufacture_year, capacity, airline_owner, maintenance_status, aircraft_history) VALUES
(1, 'Boeing 777', 2024, 353, 'Thai Airways', 'In Maintenance', 'Serious inside else memory if six. Whose group through despite cause.'),
(2, 'Boeing 787 Dreamliner', 2015, 293, 'Lufthansa', 'In Maintenance', 'Total financial role together range line beyond its.'),
(3, 'Airbus A330', 2018, 263, 'Delta Air Lines', 'Operational', 'Rest human station property. Partner stock four.'),
(4, 'Airbus A330', 2004, 298, 'Singapore Airlines', 'Retired', 'Language ball floor meet usually board necessary. Natural sport music white.'),
(5, 'Airbus A330', 2017, 295, 'Emirates', 'In Maintenance', 'Party prevent live. Quickly candidate change although.'),
(6, 'Airbus A320', 2023, 152, 'Air France', 'In Maintenance', 'Every speech support time operation wear often.'),
(7, 'Boeing 787 Dreamliner', 2003, 287, 'Qantas', 'In Maintenance', 'Picture suddenly drug rule bring determine some forward.'),
(8, 'Boeing 787 Dreamliner', 2020, 268, 'Delta Air Lines', 'In Maintenance', 'Plant view own available buy country store. Hospital have wonder already.'),
(9, 'Boeing 777', 2016, 333, 'Thai Airways', 'Retired', 'Decision song view age international big employee.'),
(10, 'Airbus A320', 2002, 173, 'Qantas', 'Retired', 'Beyond write current grow rule stuff truth college.'),
(11, 'Airbus A350', 2020, 280, 'British Airways', 'In Maintenance', 'Bring TV program actually race. Themselves true power home price check real.'),
(12, 'Boeing 737', 2023, 171, 'Singapore Airlines', 'Operational', 'Pull opportunity throughout take car. Hold increase practice ability court.'),
(13, 'Boeing 787 Dreamliner', 2007, 272, 'Emirates', 'Retired', 'I reduce industry. Close ask reduce. Month maintain no sense this manager fine.'),
(14, 'Boeing 777', 2002, 310, 'Air France', 'Retired', 'Would I question first. Add senior woman put partner.'),
(15, 'Boeing 777', 2003, 338, 'Delta Air Lines', 'In Maintenance', 'Little type physical against. Son break either president stage population boy.'),
(16, 'Airbus A350', 2003, 350, 'Air France', 'Retired', 'Fire happen nothing support suffer which parent.'),
(17, 'Boeing 737', 2019, 200, 'Lufthansa', 'In Maintenance', 'Catch even front. Responsibility full per among clearly word.'),
(18, 'Airbus A320', 2019, 175, 'Qantas', 'In Maintenance', 'Film tax rock. Idea foreign increase between training.'),
(19, 'Boeing 787 Dreamliner', 2007, 279, 'Emirates', 'Operational', 'Same thus turn phone heart window. Assume be seek article. Better news face.'),
(20, 'Boeing 737', 2001, 208, 'Lufthansa', 'In Maintenance', 'Issue grow ask tell. Total later quality. Market either political young.'),
(21, 'Airbus A320', 2002, 171, 'Emirates', 'Operational', 'Writer work chance image. There many true follow marriage material.'),
(22, 'Airbus A320', 2002, 178, 'Delta Air Lines', 'Retired', 'Stand along chance either six success.'),
(23, 'Boeing 777', 2022, 367, 'Lufthansa', 'Retired', 'Address such former claim chance. Why measure too maybe off question source.'),
(24, 'Boeing 737', 2006, 205, 'Qantas', 'Retired', 'Parent do ten after those scientist. Medical effort assume teacher wall.'),
(25, 'Airbus A330', 2014, 281, 'Air France', 'Operational', 'Expert stop area along individual. Three own bank recognize special good along.'),
(26, 'Airbus A330', 2019, 257, 'British Airways', 'Retired', 'Record power crime situation. Book art red pass value practice wide.'),
(27, 'Airbus A350', 2010, 304, 'American Airlines', 'Operational', 'Million size country site. He couple ground place what top. Main too war.'),
(28, 'Airbus A350', 2008, 294, 'American Airlines', 'In Maintenance', 'Medical watch certainly through instead base. Indeed between similar safe.'),
(29, 'Boeing 737', 2010, 184, 'Thai Airways', 'Operational', 'Try while reveal bad audience grow ahead.'),
(30, 'Boeing 737', 2022, 158, 'Thai Airways', 'Retired', 'Daughter purpose voice. Security fall ready usually.'),
(31, 'Airbus A350', 2017, 289, 'Thai Airways', 'Operational', 'Agreement decade friend which. View when player contain year.'),
(32, 'Airbus A350', 2006, 295, 'Qantas', 'Operational', 'Source firm drug senior. Head production technology over hour.'),
(33, 'Airbus A330', 2003, 252, 'Thai Airways', 'Operational', 'Instead PM be know hard we around impact. While top kid he weight before.'),
(34, 'Boeing 737', 2022, 145, 'British Airways', 'Operational', 'Up control instead company where future model.'),
(35, 'Airbus A350', 2001, 282, 'Delta Air Lines', 'In Maintenance', 'Left despite boy without feeling participant interest seem.'),
(36, 'Boeing 787 Dreamliner', 2003, 275, 'Singapore Airlines', 'Operational', 'Place again establish protect a. Moment ok how bill education exist.'),
(37, 'Airbus A320', 2020, 159, 'Air France', 'In Maintenance', 'Teacher three seven attention team executive care.'),
(38, 'Boeing 737', 2001, 194, 'British Airways', 'Operational', 'Kind nothing case but building.'),
(39, 'Boeing 787 Dreamliner', 2003, 331, 'Qantas', 'Operational', 'Major maybe manage when know central many.'),
(40, 'Airbus A330', 2011, 296, 'British Airways', 'Retired', 'According American per yourself their record. Cell of course its respond.'),
(41, 'Boeing 737', 2022, 156, 'Thai Airways', 'Retired', 'Firm decade cost glass work interview man. Somebody keep daughter report town.'),
(42, 'Boeing 737', 2005, 173, 'Delta Air Lines', 'In Maintenance', 'Sea quality do father. Relate mention expect there.'),
(43, 'Airbus A320', 2019, 179, 'British Airways', 'Retired', 'Ok majority region democratic entire analysis. Glass face according as.'),
(44, 'Boeing 737', 2000, 190, 'Qantas', 'Retired', 'Paper beat five movie. Eight miss couple bag thank generation.'),
(45, 'Boeing 787 Dreamliner', 2009, 325, 'Air France', 'In Maintenance', 'Gas Republican and various authority leave right. True include management.'),
(46, 'Airbus A350', 2008, 299, 'Delta Air Lines', 'Retired', 'Partner stand next though house where. Majority campaign that various floor.'),
(47, 'Airbus A320', 2014, 173, 'Singapore Airlines', 'In Maintenance', 'Painting movie end discussion budget situation between.'),
(48, 'Airbus A350', 2001, 349, 'Lufthansa', 'Operational', 'Business population brother. Grow push region produce develop story drive.'),
(49, 'Boeing 737', 2024, 191, 'Air France', 'Retired', 'Foreign one agent candidate how wish member. Career deal trip market.'),
(50, 'Airbus A330', 2021, 272, 'Emirates', 'Retired', 'Pick too blue street. Other majority final when new clear these.'),
(51, 'Airbus A330', 2012, 297, 'Qantas', 'Retired', 'Himself arrive although risk which.'),
(52, 'Airbus A320', 2000, 169, 'American Airlines', 'Retired', 'Ground much run. Government make article drop. Difficult president at.'),
(53, 'Airbus A330', 2005, 265, 'American Airlines', 'Retired', 'Itself group computer forget would section him.'),
(54, 'Boeing 777', 2012, 390, 'Qantas', 'Operational', 'Tv important hope about catch than method. Bag down stock computer.'),
(55, 'Boeing 777', 2022, 372, 'Qantas', 'Retired', 'Collection bad until our per leader change.'),
(56, 'Airbus A350', 2001, 301, 'British Airways', 'Operational', 'Leader medical class send. Establish manage hotel financial too nearly.'),
(57, 'Airbus A330', 2022, 260, 'British Airways', 'Retired', 'Lay return identify. Anything event yet effect quite reflect upon.'),
(58, 'Boeing 777', 2017, 377, 'Thai Airways', 'Operational', 'Not forget why under. Purpose mouth then class test check suffer star.'),
(59, 'Boeing 777', 2010, 339, 'British Airways', 'Operational', 'A cell analysis call. We lose water. Section could nature interest wear.'),
(60, 'Boeing 777', 2006, 370, 'Singapore Airlines', 'Retired', 'Place myself his itself find add sing. Watch Mrs never wrong couple.'),
(61, 'Boeing 737', 2000, 181, 'Qantas', 'In Maintenance', 'His less already treatment PM sometimes set. Gun word citizen.'),
(62, 'Airbus A320', 2006, 150, 'Thai Airways', 'Retired', 'Ever war unit back large. Tell time special beyond could key assume.'),
(63, 'Boeing 787 Dreamliner', 2019, 254, 'American Airlines', 'Operational', 'Film manage several dark. Hit simple personal home they although.'),
(64, 'Boeing 787 Dreamliner', 2020, 267, 'Lufthansa', 'In Maintenance', 'Among not girl above. Response provide likely fire subject. Fire town worker.'),
(65, 'Airbus A350', 2005, 292, 'British Airways', 'In Maintenance', 'By care lose politics. Role mind statement.'),
(66, 'Airbus A350', 2002, 282, 'Lufthansa', 'In Maintenance', 'Red effect else very your choice.'),
(67, 'Airbus A320', 2008, 154, 'Delta Air Lines', 'Retired', 'Cover social particularly speech. City four pretty live new myself star.'),
(68, 'Airbus A350', 2011, 294, 'Emirates', 'In Maintenance', 'Mention would technology budget first age. Affect though cover including.'),
(69, 'Airbus A320', 2001, 151, 'American Airlines', 'Retired', 'Group strong back approach. Page per eight finally support law.'),
(70, 'Airbus A330', 2017, 270, 'Air France', 'Retired', 'Benefit ago again identify real to. Lead network the many ball appear.'),
(71, 'Airbus A320', 2023, 180, 'British Airways', 'Retired', 'Grow better why child might source. A front war. Civil single city quite.'),
(72, 'Airbus A350', 2014, 335, 'Air France', 'Retired', 'Goal clear inside guy north. North add us accept hope soon.'),
(73, 'Boeing 737', 2006, 178, 'Lufthansa', 'Operational', 'Of challenge check skin. Industry nothing rather.'),
(74, 'Boeing 737', 2004, 164, 'Air France', 'In Maintenance', 'Probably whom it job likely different house.'),
(75, 'Airbus A330', 2022, 255, 'Air France', 'Retired', 'Single theory everybody particularly test hospital personal move.'),
(76, 'Airbus A320', 2001, 158, 'Emirates', 'Operational', 'Item bit leave left college listen. Opportunity you exist me.'),
(77, 'Boeing 787 Dreamliner', 2009, 288, 'Qantas', 'Retired', 'Computer on fast play fact. Alone improve heart decade care book.'),
(78, 'Boeing 737', 2009, 144, 'British Airways', 'Retired', 'Nation network college debate direction moment.'),
(79, 'Boeing 737', 2001, 169, 'Emirates', 'Retired', 'Significant energy citizen physical why mouth. Treatment worker season figure.'),
(80, 'Airbus A350', 2002, 318, 'Qantas', 'In Maintenance', 'Challenge on plant wonder. Blood single recently other owner message entire.'),
(81, 'Airbus A330', 2013, 256, 'Singapore Airlines', 'Retired', 'Once effect main simply two no. Sister meet though ago.'),
(82, 'Boeing 777', 2015, 343, 'Air France', 'Operational', 'Enough onto try commercial kid approach. Upon beautiful open free medical lay.'),
(83, 'Boeing 777', 2003, 389, 'British Airways', 'In Maintenance', 'City system story century attention attention.'),
(84, 'Airbus A320', 2009, 160, 'Emirates', 'Operational', 'Speech catch ten statement carry next. Almost identify record.'),
(85, 'Airbus A350', 2018, 328, 'Singapore Airlines', 'Operational', 'Marriage worker ever across great.'),
(86, 'Airbus A320', 2006, 173, 'American Airlines', 'Operational', 'Discuss very score loss. Executive partner story budget great than.'),
(87, 'Boeing 777', 2000, 312, 'Qantas', 'Retired', 'Should research executive black tough building. General during cost what.'),
(88, 'Boeing 787 Dreamliner', 2009, 299, 'British Airways', 'Retired', 'Determine human find discussion military ability line hour.'),
(89, 'Airbus A350', 2021, 307, 'Qantas', 'Operational', 'Customer force both something hair. Well account movement can start.'),
(90, 'Airbus A330', 2007, 266, 'Emirates', 'In Maintenance', 'Unit dinner indeed listen. Job high she.'),
(91, 'Boeing 737', 2011, 144, 'Singapore Airlines', 'Retired', 'War resource evening realize per. Her of process cut.'),
(92, 'Airbus A320', 2016, 164, 'American Airlines', 'Operational', 'Fund indicate help north friend state do. Go simple improve language thousand.'),
(93, 'Boeing 777', 2012, 332, 'American Airlines', 'Retired', 'Growth main use chance story. Could usually piece but.'),
(94, 'Airbus A320', 2006, 169, 'Emirates', 'Operational', 'Hope could many cold another way sign. Thought radio minute rich consumer type.'),
(95, 'Boeing 737', 2014, 178, 'Air France', 'Retired', 'Toward such new cultural analysis care kitchen.'),
(96, 'Boeing 737', 2003, 206, 'British Airways', 'Operational', 'Management court head successful response hospital.'),
(97, 'Boeing 787 Dreamliner', 2012, 323, 'Qantas', 'Retired', 'Week remain decide happy another image. Take one them in.'),
(98, 'Boeing 777', 2021, 341, 'British Airways', 'In Maintenance', 'Herself Mr bad wide manage. Daughter pay growth. Seat should dream whose.'),
(99, 'Airbus A350', 2021, 305, 'Delta Air Lines', 'Retired', 'Election order everything stuff detail himself medical.'),
(100, 'Boeing 737', 2000, 173, 'Air France', 'In Maintenance', 'As year look floor role agency its. Seven those budget involve.'),
(101, 'Airbus A320', 2016, 154, 'Lufthansa', 'Retired', 'Health sort couple station my. Middle add traditional standard PM election.'),
(102, 'Boeing 737', 2012, 204, 'Lufthansa', 'Retired', 'Edge bit avoid yourself. Magazine minute site girl.'),
(103, 'Airbus A350', 2015, 288, 'Singapore Airlines', 'Retired', 'Give especially win give yourself system. Letter finish campaign night simply.'),
(104, 'Airbus A320', 2002, 157, 'Emirates', 'Operational', 'Along particularly factor boy Republican without.'),
(105, 'Airbus A330', 2000, 298, 'British Airways', 'In Maintenance', 'You company drop join recognize all structure.'),
(106, 'Boeing 737', 2004, 213, 'British Airways', 'In Maintenance', 'Any remain support realize cause.'),
(107, 'Boeing 787 Dreamliner', 2012, 309, 'Delta Air Lines', 'Operational', 'Interest college anything relationship.'),
(108, 'Boeing 787 Dreamliner', 2002, 328, 'Delta Air Lines', 'Retired', 'Moment buy east example identify likely. Clearly thought modern dark.'),
(109, 'Airbus A320', 2023, 163, 'American Airlines', 'In Maintenance', 'Name Congress ten return understand. During nice thing ok.'),
(110, 'Boeing 787 Dreamliner', 2019, 295, 'British Airways', 'In Maintenance', 'Reveal so suggest. Include herself hold his.'),
(111, 'Boeing 787 Dreamliner', 2018, 271, 'Thai Airways', 'Retired', 'Second late every include generation. Election baby seven only scientist teach.'),
(112, 'Airbus A320', 2023, 155, 'Lufthansa', 'Retired', 'Report to product outside they eye out. Project happen white maybe read card.'),
(113, 'Boeing 787 Dreamliner', 2008, 284, 'Singapore Airlines', 'In Maintenance', 'Visit red forward table owner. Official receive may push serious successful.'),
(114, 'Airbus A330', 2009, 299, 'Qantas', 'In Maintenance', 'Sing media step live game item lay.'),
(115, 'Boeing 777', 2001, 320, 'Emirates', 'Operational', 'Without wall stay describe time.'),
(116, 'Airbus A330', 2023, 271, 'Thai Airways', 'Operational', 'Story financial state hotel. Scene teach because it boy agent common.'),
(117, 'Boeing 777', 2013, 318, 'British Airways', 'Retired', 'Option imagine physical treat dinner able job page.'),
(118, 'Airbus A350', 2002, 299, 'Air France', 'In Maintenance', 'Country article will firm woman section magazine loss.'),
(119, 'Airbus A320', 2019, 164, 'Qantas', 'In Maintenance', 'Resource part instead city type short rather. Once born control white.'),
(120, 'Airbus A320', 2003, 165, 'Emirates', 'Operational', 'Meeting movie avoid American address simply. Thousand impact six loss.'),
(121, 'Airbus A320', 2019, 169, 'Emirates', 'Retired', 'Popular see different decide trip total. Out human night.'),
(122, 'Airbus A330', 2003, 294, 'Delta Air Lines', 'Retired', 'There certainly walk camera debate western store.'),
(123, 'Airbus A330', 2006, 274, 'British Airways', 'Operational', 'Then police choice cell. Care yet well according star study form.'),
(124, 'Airbus A320', 2019, 172, 'British Airways', 'Retired', 'Movie base firm himself idea lose international.'),
(125, 'Airbus A350', 2010, 295, 'Lufthansa', 'Operational', 'Challenge audience choose himself north professional.'),
(126, 'Boeing 777', 2009, 395, 'Singapore Airlines', 'Retired', 'Level generation since also himself with garden mention.'),
(127, 'Boeing 737', 2001, 180, 'British Airways', 'In Maintenance', 'Million born American. Always hand game magazine series think.'),
(128, 'Boeing 737', 2014, 175, 'Singapore Airlines', 'Operational', 'Two seven lose probably. Strategy receive rate oil.'),
(129, 'Airbus A320', 2015, 158, 'Thai Airways', 'Retired', 'Particularly firm foreign involve.'),
(130, 'Airbus A350', 2018, 307, 'American Airlines', 'Operational', 'Walk draw front plan focus century. Nearly movie report boy two.'),
(131, 'Airbus A350', 2024, 344, 'Delta Air Lines', 'In Maintenance', 'Hope memory government image room. Court culture story.'),
(132, 'Boeing 787 Dreamliner', 2009, 256, 'Emirates', 'In Maintenance', 'Approach trip throughout free civil entire.'),
(133, 'Boeing 787 Dreamliner', 2013, 252, 'Singapore Airlines', 'In Maintenance', 'Yet so before wrong. Message western stage yes too dog among believe.'),
(134, 'Airbus A320', 2003, 163, 'Emirates', 'Retired', 'Most ten cup far training opportunity difficult candidate.'),
(135, 'Airbus A320', 2014, 163, 'Qantas', 'Operational', 'Together professional wind consider.'),
(136, 'Boeing 777', 2010, 392, 'Lufthansa', 'Operational', 'Social say about century debate. Push industry certainly Mrs me wear prove.'),
(137, 'Airbus A330', 2002, 257, 'Air France', 'Retired', 'Majority good open executive experience hotel. Heart west training believe.'),
(138, 'Airbus A320', 2011, 161, 'Emirates', 'Operational', 'Crime social school enter wind heavy anything.'),
(139, 'Boeing 737', 2011, 139, 'Emirates', 'Operational', 'Figure kitchen seven. Decision data wrong best I medical.'),
(140, 'Airbus A320', 2006, 171, 'Singapore Airlines', 'Retired', 'Defense cup man course teacher message page.'),
(141, 'Airbus A320', 2009, 161, 'Thai Airways', 'Retired', 'Owner ahead generation shoulder day popular window key.'),
(142, 'Boeing 737', 2004, 153, 'British Airways', 'Operational', 'Forget result professor research theory become. Step have perform because.'),
(143, 'Boeing 777', 2011, 390, 'Lufthansa', 'Operational', 'Military plan school certainly. Focus raise away tough subject customer far.'),
(144, 'Airbus A320', 2006, 161, 'Air France', 'In Maintenance', 'Money store majority choice. Then investment scientist bring.'),
(145, 'Airbus A330', 2009, 285, 'Air France', 'Operational', 'Federal like be. Positive better management minute air represent.'),
(146, 'Boeing 787 Dreamliner', 2002, 255, 'Delta Air Lines', 'Retired', 'Way sister civil market value during difficult religious.'),
(147, 'Airbus A330', 2005, 274, 'Emirates', 'Operational', 'Per attack evidence especially life sister official yeah.'),
(148, 'Boeing 737', 2010, 195, 'American Airlines', 'Operational', 'Hospital against fast drop simply or. Easy mission laugh wind. She inside mind.'),
(149, 'Boeing 737', 2009, 177, 'Qantas', 'Retired', 'Fear knowledge player down positive. Be certain ago whom language.'),
(150, 'Airbus A320', 2004, 169, 'Thai Airways', 'In Maintenance', 'Environment style remain. Machine likely middle car market.');
