INSERT INTO aircraft (aircraft_id, model, manufacture_year, capacity, airline_owner, maintenance_status, aircraft_history) VALUES
(1, 'Boeing 777', 2013, 397, 'Thai Airways', 'Maintenance', 'Together range line beyond. First policy daughter need kind miss.'),
(2, 'Boeing 787 Dreamliner', 2012, 304, 'Lufthansa', 'Maintenance', 'Language ball floor meet usually board necessary. Natural sport music white.'),
(3, 'Airbus A330', 2006, 287, 'Delta Air Lines', 'Active', 'Small citizen class morning. Others kind company likely.'),
(4, 'Airbus A330', 2024, 258, 'Singapore Airlines', 'Retired', 'Security stock ball organization recognize civil. Pm her then nothing increase.'),
(5, 'Airbus A330', 2022, 284, 'Emirates', 'Maintenance', 'First degree response able state more. Couple part cup few. Beyond take however ball.'),
(6, 'Airbus A320', 2002, 173, 'Air France', 'Maintenance', 'Water voice travel among see red. Republican total policy head Mrs debate onto. Catch even front.'),
(7, 'Boeing 787 Dreamliner', 2011, 254, 'Qantas', 'Maintenance', 'Buy break marriage also friend reach. Turn phone heart window. Assume be seek article.'),
(8, 'Boeing 787 Dreamliner', 2006, 323, 'Delta Air Lines', 'Maintenance', 'Work chance image quite there many true follow. Your play themselves myself use act relationship.'),
(9, 'Boeing 777', 2008, 366, 'Thai Airways', 'Retired', 'Now four management energy stay significant his. Artist political camera expert stop area.'),
(10, 'Airbus A320', 2023, 152, 'Qantas', 'Retired', 'Partner hit another. Sing after our car food record power. Himself simply make thing particular.'),
(11, 'Airbus A350', 2019, 280, 'British Airways', 'Maintenance', 'Between similar safe air. Issue indicate market ten foot education good. Grow ahead girl act.'),
(12, 'Boeing 737', 2022, 171, 'Singapore Airlines', 'Active', 'Cost both general where. Agreement decade friend which.'),
(13, 'Boeing 787 Dreamliner', 2007, 270, 'Emirates', 'Retired', 'Information animal car after back available. Federal indicate unit opportunity fear great.'),
(14, 'Boeing 777', 2002, 311, 'Air France', 'Retired', 'Painting child reflect up control instead company. Future model green place beat sense far.'),
(15, 'Boeing 777', 2009, 313, 'Delta Air Lines', 'Maintenance', 'Feel seat appear perform agent likely. Suffer without rather.'),
(16, 'Airbus A350', 2017, 295, 'Air France', 'Retired', 'Former possible reach challenge. Model can travel know. Interview man role somebody keep daughter.'),
(17, 'Boeing 737', 2017, 207, 'Lufthansa', 'Maintenance', 'Front amount apply glass face. Cell skill quite. However TV law fund bill third some follow.'),
(18, 'Airbus A320', 2012, 169, 'Air France', 'Retired', 'Without leave brother bank better she.'),
(19, 'Boeing 737', 2005, 167, 'American Airlines', 'Active', 'Happen play speech theory choice computer. Career deal trip market. Dog car do his part.'),
(20, 'Airbus A320', 2021, 169, 'Lufthansa', 'Maintenance', 'Page region start size. Want decade firm section economic television.'),
(21, 'Airbus A320', 2021, 152, 'Emirates', 'Active', 'Will institution throughout describe itself group. Power road size impact.'),
(22, 'Airbus A320', 2002, 176, 'Delta Air Lines', 'Retired', 'Important hope about catch. Style record bag down stock computer watch. Sea stuff no response.'),
(23, 'Boeing 777', 2016, 390, 'Lufthansa', 'Retired', 'Significant now energy. Lay return identify. Anything event yet effect quite reflect upon.'),
(24, 'Boeing 737', 2021, 157, 'Qantas', 'Retired', 'Suffer star once anything choose general. Personal follow situation over would.'),
(25, 'Airbus A330', 2015, 278, 'Air France', 'Active', 'Section could nature interest wear. Morning as police often. Place myself his itself find add sing.'),
(26, 'Airbus A330', 2003, 289, 'British Airways', 'Retired', 'Guess we no in pass sound. Tonight gun word citizen create. Physical market room eat through ever.'),
(27, 'Airbus A350', 2006, 322, 'American Airlines', 'Active', 'Action economy several hit simple personal home.
Let stop camera report foreign agency list miss.'),
(28, 'Airbus A350', 2003, 314, 'American Airlines', 'Maintenance', 'Likely fire subject west agent hotel by. Image central challenge term memory.'),
(29, 'Boeing 737', 2013, 172, 'Thai Airways', 'Active', 'Particularly speech mission remember tree care sign. Myself star gas spend.'),
(30, 'Boeing 737', 2001, 158, 'Delta Air Lines', 'Retired', 'We ask benefit ago again. Pattern president add lead network the.'),
(31, 'Airbus A350', 2000, 289, 'Singapore Airlines', 'Retired', 'Heavy church nature.'),
(32, 'Boeing 737', 2018, 207, 'Singapore Airlines', 'Maintenance', 'Difficult there leg theory case north. Class on reach.'),
(33, 'Airbus A320', 2003, 161, 'Thai Airways', 'Retired', 'Job trial four easy case member.'),
(34, 'Airbus A320', 2005, 156, 'Singapore Airlines', 'Maintenance', 'American focus something who blood. Certain hotel should.'),
(35, 'Boeing 737', 2021, 137, 'Thai Airways', 'Retired', 'Issue radio especially road get car party. All office less politics.'),
(36, 'Boeing 777', 2003, 379, 'Lufthansa', 'Active', 'Important produce just raise enough onto try. Those north trouble upon.'),
(37, 'Boeing 737', 2020, 139, 'Lufthansa', 'Maintenance', 'Attention attention hotel well news enter director. Father growth behind probably.'),
(38, 'Boeing 777', 2001, 323, 'Delta Air Lines', 'Maintenance', 'Stuff find different many water meeting future. Fight institution school white.'),
(39, 'Airbus A320', 2003, 169, 'Qantas', 'Active', 'Customer force both something hair. Well account movement can start.'),
(40, 'Airbus A330', 2023, 272, 'British Airways', 'Retired', 'Agency center sign career debate. Cut meet build black treat buy.'),
(41, 'Boeing 737', 2024, 156, 'Thai Airways', 'Retired', 'Drop local cell kid growth main. Why mission because feel.'),
(42, 'Boeing 737', 2010, 150, 'Delta Air Lines', 'Maintenance', 'Tell mention check election order everything stuff detail.'),
(43, 'Airbus A320', 2014, 169, 'Emirates', 'Active', 'Evening his gas health sort couple station my.'),
(44, 'Boeing 777', 2013, 387, 'Delta Air Lines', 'Maintenance', 'Stock worker everybody professor show bar standard. The site follow be add.'),
(45, 'Airbus A350', 2012, 325, 'Lufthansa', 'Active', 'Pick purpose expert age account. Away wish finish within president.'),
(46, 'Boeing 787 Dreamliner', 2000, 330, 'British Airways', 'Retired', 'Discussion star individual third.'),
(47, 'Airbus A320', 2023, 160, 'Thai Airways', 'Retired', 'Include herself hold his. Manage camera beat activity stay bank which.'),
(48, 'Airbus A330', 2007, 258, 'British Airways', 'Maintenance', 'Speak really eat report to product outside.'),
(49, 'Boeing 787 Dreamliner', 2021, 278, 'Air France', 'Retired', 'Smile create either. Adult others talk without. Stay describe time.'),
(50, 'Airbus A350', 2022, 296, 'Lufthansa', 'Maintenance', 'Mother good decade TV culture continue condition probably.'),
(51, 'Airbus A350', 2020, 333, 'Singapore Airlines', 'Active', 'Part instead city type short rather. Once born control white. Rather beyond share energy size.'),
(52, 'Boeing 787 Dreamliner', 2022, 266, 'Air France', 'Active', 'Site car room father identify within street national.'),
(53, 'Boeing 737', 2020, 158, 'British Airways', 'Maintenance', 'According star study form seem beat. Effect forward magazine movie base.'),
(54, 'Airbus A350', 2001, 333, 'Qantas', 'Retired', 'Your outside wish community kid official within.'),
(55, 'Boeing 787 Dreamliner', 2024, 295, 'Thai Airways', 'Active', 'Before wrong take old former run others believe. Dog among believe value fine staff that.'),
(56, 'Boeing 777', 2008, 308, 'Emirates', 'Maintenance', 'Wind consider that admit Mrs look. Sense scientist bank result.'),
(57, 'Boeing 787 Dreamliner', 2017, 304, 'Thai Airways', 'Active', 'Box operation prepare might catch that. Century energy safe crime social school enter.'),
(58, 'Boeing 777', 2009, 341, 'British Airways', 'Active', 'Cut drive out. Attorney stock defense cup man course.'),
(59, 'Boeing 777', 2017, 324, 'Singapore Airlines', 'Retired', 'Window key military. Stay century law before everybody.'),
(60, 'Boeing 737', 2012, 131, 'Qantas', 'Maintenance', 'Tv drive adult executive military plan. Break focus raise away.'),
(61, 'Airbus A320', 2000, 156, 'Thai Airways', 'Retired', 'Could own glass one then investment scientist. Walk cause trouble movie.'),
(62, 'Boeing 787 Dreamliner', 2003, 320, 'American Airlines', 'Active', 'Believe performance officer election information. Remain center without.'),
(63, 'Boeing 787 Dreamliner', 2006, 325, 'Lufthansa', 'Maintenance', 'She inside mind. Represent resource pretty write. Fear knowledge player down positive.'),
(64, 'Airbus A350', 2003, 303, 'British Airways', 'Maintenance', 'Job follow result. Form single camera political economic.'),
(65, 'Airbus A350', 2000, 290, 'Lufthansa', 'Maintenance', 'Color everything buy protect front why ability fund. Laugh cup hear prove leave national.'),
(66, 'Airbus A320', 2008, 177, 'Emirates', 'Retired', 'Inside water do get finish pick shake level.'),
(67, 'Boeing 787 Dreamliner', 2020, 325, 'Air France', 'Active', 'Staff week own necessary allow. Throughout society theory happy culture daughter.'),
(68, 'Boeing 737', 2000, 165, 'Thai Airways', 'Active', 'Key when also long time blood. List run safe figure.'),
(69, 'Boeing 737', 2017, 163, 'Air France', 'Maintenance', 'Far around almost. Choose order college. One after score career.'),
(70, 'Boeing 787 Dreamliner', 2023, 247, 'British Airways', 'Retired', 'World believe soldier certain edge. Play pay real good human. Whatever simple wrong newspaper.'),
(71, 'Airbus A350', 2020, 338, 'Qantas', 'Maintenance', 'Season environment bag. Possible account question dinner write usually.'),
(72, 'Boeing 787 Dreamliner', 2006, 264, 'Qantas', 'Retired', 'Commercial identify on stand trip all. Send through law national last people friend.'),
(73, 'Airbus A330', 2004, 250, 'Emirates', 'Maintenance', 'As usually training able treat. Better child computer either.'),
(74, 'Airbus A330', 2011, 271, 'Singapore Airlines', 'Maintenance', 'Create agree likely off anything pick. Career election few turn think tree amount.'),
(75, 'Boeing 787 Dreamliner', 2001, 246, 'Lufthansa', 'Active', 'It manage heavy investment day interest side. Author carry focus fact special.'),
(76, 'Boeing 737', 2009, 204, 'Air France', 'Maintenance', 'Tv character build identify. Example office between table.'),
(77, 'Boeing 787 Dreamliner', 2009, 258, 'Singapore Airlines', 'Maintenance', 'Care door natural produce team operation. Top worry there similar adult range true.'),
(78, 'Airbus A350', 2001, 310, 'Lufthansa', 'Active', 'Investment science task spend candidate whose. Couple year person understand back use me.'),
(79, 'Boeing 787 Dreamliner', 2002, 335, 'Lufthansa', 'Maintenance', 'Decide grow between heavy by of mission. Difference others know expert cell style believe tough.'),
(80, 'Airbus A330', 2013, 269, 'Singapore Airlines', 'Active', 'Unit operation foreign loss manage each. General college bed everybody.'),
(81, 'Boeing 787 Dreamliner', 2015, 303, 'Air France', 'Maintenance', 'Speak lay born. Form parent majority know participant. Increase ago surface weight.'),
(82, 'Airbus A320', 2003, 165, 'British Airways', 'Maintenance', 'Economic attack food laugh newspaper part better. Specific city paper part.'),
(83, 'Airbus A320', 2010, 159, 'Emirates', 'Active', 'Speech other question indeed message picture study. Full road nothing defense customer.'),
(84, 'Airbus A350', 2020, 328, 'Singapore Airlines', 'Active', 'People point month smile. Indicate actually small case middle resource project.'),
(85, 'Airbus A320', 2023, 156, 'American Airlines', 'Active', 'True discussion without current rate. Movement edge collection which.'),
(86, 'Boeing 777', 2003, 301, 'Qantas', 'Retired', 'Rule sometimes serve community tonight. Vote support much ready back.'),
(87, 'Boeing 787 Dreamliner', 2014, 279, 'British Airways', 'Retired', 'Improve son less. Attention both hour factor.'),
(88, 'Airbus A350', 2013, 307, 'Singapore Airlines', 'Maintenance', 'Movement certainly group member. Since use out cost game set.'),
(89, 'Boeing 737', 2018, 163, 'Emirates', 'Maintenance', 'Mission recently value expert thing bed among. Else represent detail open future rich.'),
(90, 'Boeing 737', 2003, 175, 'Singapore Airlines', 'Retired', 'Should property ten many fine so. Finish pressure recognize would pattern still simply.'),
(91, 'Airbus A320', 2016, 178, 'British Airways', 'Retired', 'Environment land trouble staff follow baby job. Sea speak subject yet forget open.'),
(92, 'Boeing 737', 2015, 145, 'Qantas', 'Maintenance', 'Simply wait similar blood really child lead.'),
(93, 'Boeing 737', 2001, 212, 'American Airlines', 'Retired', 'Knowledge her ten structure foot question.'),
(94, 'Boeing 737', 2006, 143, 'British Airways', 'Maintenance', 'Five modern there resource box during.'),
(95, 'Airbus A330', 2004, 284, 'Singapore Airlines', 'Retired', 'Form nor affect some various watch choice cause. Cost home hard general nor administration open.'),
(96, 'Boeing 777', 2018, 318, 'Qantas', 'Retired', 'Guess what edge change structure. Outside voice measure under. Old nice per pattern group life.'),
(97, 'Airbus A350', 2016, 334, 'British Airways', 'Retired', 'Test direction call adult toward small finish. Meet despite nothing agreement receive even.'),
(98, 'Airbus A330', 2015, 281, 'American Airlines', 'Retired', 'Everything war he including. Require night personal sure whether visit.'),
(99, 'Boeing 787 Dreamliner', 2000, 270, 'Air France', 'Retired', 'Gas right yes American call statement specific. Special might wish street space human.'),
(100, 'Airbus A350', 2010, 320, 'Thai Airways', 'Retired', 'Now population in full billion rise. Event under same commercial.'),
(101, 'Boeing 737', 2019, 162, 'Emirates', 'Maintenance', 'Former perform whose better themselves field. Assume hot chance foot candidate case research.'),
(102, 'Boeing 787 Dreamliner', 2022, 279, 'British Airways', 'Active', 'Last dark power energy. Course laugh civil degree now go energy.'),
(103, 'Airbus A320', 2001, 166, 'Singapore Airlines', 'Active', 'Eye fire growth alone until. Occur person social. Apply western feeling.'),
(104, 'Boeing 737', 2009, 135, 'Thai Airways', 'Maintenance', 'Sea worker store successful field crime. Impact move firm industry let. Ever voice hotel at week.'),
(105, 'Airbus A330', 2004, 260, 'British Airways', 'Maintenance', 'Everybody rock after level pattern side.
Cold team miss. Before tell ago question left meeting.'),
(106, 'Boeing 787 Dreamliner', 2016, 290, 'Delta Air Lines', 'Active', 'Scene arrive whatever wrong to. One sort blue since long economic tough also.'),
(107, 'Boeing 787 Dreamliner', 2021, 253, 'Delta Air Lines', 'Retired', 'Step inside so section reveal structure chair. Impact no almost international.'),
(108, 'Airbus A320', 2013, 173, 'American Airlines', 'Maintenance', 'Music rest until new enter message reason. Himself already person strategy large.'),
(109, 'Boeing 787 Dreamliner', 2013, 318, 'British Airways', 'Maintenance', 'Happen discover she shoulder. Government choice before Democrat among hotel service.'),
(110, 'Boeing 787 Dreamliner', 2007, 317, 'Thai Airways', 'Retired', 'However picture agree pass report through. Note fear him.'),
(111, 'Airbus A320', 2005, 173, 'Lufthansa', 'Retired', 'Answer treatment another institution whose before. Like decide environment adult listen another.'),
(112, 'Boeing 787 Dreamliner', 2010, 274, 'Singapore Airlines', 'Maintenance', 'Traditional probably article last forward. Article probably answer argue.'),
(113, 'Airbus A330', 2024, 269, 'Qantas', 'Maintenance', 'Question theory per deep method federal easy. Government big increase interest.'),
(114, 'Boeing 777', 2005, 307, 'Emirates', 'Active', 'Against some foreign. Same wall wife before eight arm seven interest.'),
(115, 'Airbus A330', 2010, 296, 'Thai Airways', 'Active', 'Nature another check group indeed feel should whose. School yard quality production cause music.'),
(116, 'Boeing 777', 2004, 353, 'British Airways', 'Retired', 'Tv between camera live. Trip occur accept technology all describe coach.'),
(117, 'Airbus A350', 2021, 290, 'Emirates', 'Maintenance', 'Offer present pretty language. Environment different some another run wall force.'),
(118, 'Boeing 777', 2019, 304, 'British Airways', 'Maintenance', 'Break debate fear degree use day. Office similar its foot tonight. Drive minute according capital.'),
(119, 'Boeing 777', 2003, 306, 'British Airways', 'Active', 'Week like mean. Determine response wide method movie painting. Rate measure brother approach five.'),
(120, 'Airbus A320', 2019, 151, 'Emirates', 'Retired', 'Small create day party. Strong term main feeling bag.'),
(121, 'Airbus A330', 2022, 256, 'Delta Air Lines', 'Retired', 'Left piece time on expert must small. Better those ability serve least mother.'),
(122, 'Airbus A330', 2012, 262, 'British Airways', 'Active', 'Charge or put upon rather claim also. Good from glass type structure so magazine.'),
(123, 'Airbus A320', 2022, 169, 'British Airways', 'Retired', 'Note land lead not site first. Long civil anything court many ability. Clear deep scientist rather.'),
(124, 'Airbus A350', 2020, 323, 'Singapore Airlines', 'Retired', 'Social example state into change treatment figure program. Office her program.'),
(125, 'Airbus A350', 2004, 317, 'Qantas', 'Maintenance', 'Type rest name term turn unit. Peace spend up simple wind.'),
(126, 'Airbus A350', 2016, 295, 'American Airlines', 'Active', 'Beat yourself find available.'),
(127, 'Boeing 777', 2011, 356, 'American Airlines', 'Maintenance', 'Affect partner seek up chance. Stuff rock foreign pressure maybe.'),
(128, 'Airbus A330', 2020, 300, 'Singapore Airlines', 'Active', 'Dinner alone body front indicate central himself can. Discuss health stop law.'),
(129, 'Airbus A320', 2008, 165, 'Thai Airways', 'Retired', 'Source discuss create policy service area. Either hold base arm upon one.'),
(130, 'Airbus A350', 2007, 307, 'Singapore Airlines', 'Retired', 'Evening whom remain. Bill imagine former day TV situation.'),
(131, 'Boeing 787 Dreamliner', 2016, 331, 'Qantas', 'Retired', 'Section can draw culture all glass loss. North follow few if available sister.'),
(132, 'Airbus A330', 2004, 257, 'Qantas', 'Retired', 'Similar third over sometimes street pressure son time. Statement catch language help yeah.'),
(133, 'Boeing 777', 2003, 310, 'Qantas', 'Active', 'Talk some third positive certain available car more. Financial animal while kid chair maybe hold.'),
(134, 'Airbus A320', 2024, 163, 'Emirates', 'Retired', 'Easy describe imagine treatment bank.'),
(135, 'Airbus A320', 2014, 175, 'Qantas', 'Retired', 'Part manager film approach admit rest. Produce decision dinner physical.'),
(136, 'Boeing 777', 2015, 303, 'Air France', 'Retired', 'Newspaper thought must. Can beautiful arrive usually can.'),
(137, 'Airbus A330', 2011, 255, 'Singapore Airlines', 'Active', 'Account join that thing. Stuff Congress suffer out total black budget certain.'),
(138, 'Airbus A330', 2000, 294, 'Air France', 'Maintenance', 'Responsibility forget board term too. Their event whose white him child. Admit common fish part.'),
(139, 'Boeing 737', 2007, 131, 'Air France', 'Active', 'Pressure ball financial field. Pay marriage model exist data send.'),
(140, 'Boeing 787 Dreamliner', 2006, 260, 'Thai Airways', 'Active', 'Dream four probably.
Pm event wait describe four blood make. Inside see wait myself before.'),
(141, 'Airbus A350', 2023, 295, 'Thai Airways', 'Maintenance', 'Event even style send company describe. Single hundred let believe attorney.'),
(142, 'Airbus A330', 2000, 294, 'American Airlines', 'Active', 'Thousand build join red political should. Let responsibility different. Option long beat than.'),
(143, 'Boeing 737', 2003, 188, 'British Airways', 'Maintenance', 'Use friend during hot. Half lay week charge. Thank boy find.'),
(144, 'Airbus A350', 2004, 313, 'Thai Airways', 'Active', 'Large different listen draw. Body friend central.
Staff better final state.'),
(145, 'Airbus A330', 2015, 271, 'Lufthansa', 'Maintenance', 'Blood born culture assume read. You entire prepare into build either relate.'),
(146, 'Boeing 787 Dreamliner', 2010, 323, 'Emirates', 'Retired', 'In step guess pattern production face if one. Region different leave act range live along.'),
(147, 'Airbus A320', 2017, 153, 'Lufthansa', 'Active', 'He author vote Republican century discussion. Improve good save return father they hear very.'),
(148, 'Boeing 777', 2004, 318, 'American Airlines', 'Maintenance', 'Could maintain position animal close.'),
(149, 'Boeing 787 Dreamliner', 2007, 273, 'Emirates', 'Maintenance', 'Significant debate front free long hot. Discuss stay machine strong just.'),
(150, 'Airbus A330', 2021, 276, 'Thai Airways', 'Active', 'After art tell idea accept. Go trade control should two meet other. Stage reach story case.');